export const CONFIG = {
  render: {
    clearColor: 0x070f1a,
    pixelRatioCap: 1.75,
  },
  table: {
    width: 20,
    length: 34,
    thickness: 1.2,
    surfaceY: 0.62,
    wallHeight: 1.05,
    wallThickness: 0.64,
    centerLineWidth: 0.1,
  },
  goal: {
    slotWidth: 4.8,
    pocketDepth: 1.4,
    scoreDepthFactor: 0.55,
  },
  paddle: {
    radius: 1.08,
    height: 0.5,
    mass: 2.4,
    maxSpeed: 52,
    acceleration: 210,
    linearDamping: 0.9,
    aiMaxSpeed: 48,
    aiAcceleration: 145,
    aiLinearDamping: 0.9,
    aiProMaxSpeed: 64,
    aiProAcceleration: 220,
    aiProLinearDamping: 0.95,
    aiCornerAssistOffset: 2.1,
    aiPressureTime: 0.62,
    aiReengageTime: 0.22,
    aiDangerZoneDepth: 3.4,
    aiDangerExitSpeed: 1.2,
    aiShotLaneWidth: 3.2,
    aiPushDistance: 1.1,
    aiHitReward: 0.45,
    aiHitPenalty: 0.7,
    aiRewardDecayPerSecond: 0.26,
  },
  ball: {
    radius: 0.52,
    height: 0.22,
    mass: 1,
    serveSpeed: 14,
    maxSpeed: 86,
    linearDamping: 0.9995,
    wallRestitution: 0.93,
    discRestitution: 0.97,
    serveAngleMax: 0.35,
    cornerEscapeSpeed: 6.5,
    cornerEscapeThreshold: 0.34,
    stuckSpeedThreshold: 0.75,
  },
  physics: {
    maxTravelPerStep: 0.55,
    maxSubsteps: 8,
  },
  camera: {
    fov: 58,
    offset: { x: 0, y: 7.1, z: 12.2 },
    smoothness: 0.14,
    lookAhead: 9.8,
  },
  match: {
    targetScore: 7,
    serveDelay: 1.1,
  },
};
